-- importing excel data in sql developer 
-- tables->import data-> browes-> excel file.
-- displaying customers111 data 
select * from customers111;s

--Removing duplicate customer records.
delete from customers111 where rowid not in (
select min(rowid) from customers111 group by customer_id);

-- Replace NULLs in REVIEW_RATING with average rating
update customers111
set review_rating=(select round(avg(review_rating),1) from customers111 where review_rating is null);

-- Replace NULLs in SIZE1 with 'Unknown'
update customers111 set size1='unknown' where size1 is null;

-- Replace NULLs in COLOR with 'No Color'
update customers111 set color='no colour' where color is null;

--Ensure valid values in numeric fields
update customers111 set purchase_amount_usd=0 where purchase_amount_usd<0 or purchase_amount_usd is null;

---- Trim and capitalizing GENDER and CATEGORY
update customers111 set gender = initcap(trim(gender)),
category = initcap(trim(category)),
location = initcap(trim(location));

--Show the names of all products purchased in the 'Clothing' category.
select item_purchased from customers111 where category = 'Clothing';

--Find the total number of purchases made using the 'Credit Card' payment method.
select count(*) as credit_card_purchases from customers111 where PAYMENT_METHOD  = 'Credit Card';

--Display names of all customers who bought items in 'Spring' season and paid more than ₹50.
select customer_id, item_purchased, purchase_amount_usd
from customers111
where season = 'Spring' and purchase_amount_usd > 50;

-- List distinct cities where purchases were made.
select distinct location from customers111;

--Show total revenue generated by each category.
select category, sum(purchase_amount_usd) as total_revenue
from customers111
group by category;

 --Show average review rating by gender and season.
select gender, season, round(avg(review_rating), 2) as avg_rating
from customers111
group by gender, season;

--Rank customers based on their purchase amount (highest first).
select customer_id, purchase_amount_usd,rank()
over (order by purchase_amount_usd desc) as purchase_rank
from customers111;

-- List the top 5 biggest spenders.
select *
from (
select customer_id, purchase_amount_usd
from customers111 order by purchase_amount_usd desc)where rownum <= 5;

--Create a view showing customer segments based on spend:
create or replace view customer_segments as select customer_id, purchase_amount_usd,
case
when purchase_amount_usd >= 75 then 'High'
when purchase_amount_usd between 40 and 74 then 'Medium'
else 'Low'
end as segment
from customers111;
select * from customer_segments;


--List all items with 'a' at the second position in item name.
select item_purchased
from customers111
where item_purchased like '_a%';

--Show total number of purchases per color, sorted descending.
select color, count(*) as total_sold
from customers111
group by color
order by total_sold desc;

--Find the most purchased category in each season
select season, category, count(*) as purchases,rank()
over (partition by season order by count(*) desc) as rank_in_season
from customers111
group by season, category;

--Total customers & total purchases
select count(distinct customer_id) as total_customers,
count(*) as total_purchases
from customers111;

--Top 5 most purchased product categories
select category, count(*) as total_sold
from customers111
group by category
order by total_sold desc fetch first 3 rows only;

--Top 10 customers by spend using RANK
select customer_id, purchase_amount_usd,rank()
over (order by purchase_amount_usd desc) as purchase_rank
from customers111
fetch first 10 rows only;

-- adding table to perform join operations
create table products_master (
product_id number primary key,
item_name varchar2(100),
category varchar2(50),
base_price number
);

create table customer_details (
customer_id number primary key,
full_name varchar2(100),
email varchar2(100),
join_date date
);

insert into products_master values (101, 'T-Shirt', 'Clothing', 15);
insert into products_master values (102, 'Jacket', 'Clothing', 50);
insert into products_master values (103, 'Sneakers', 'Footwear', 40);
insert into products_master values (104, 'Backpack', 'Accessories', 25);
insert into products_master values (105, 'Watch', 'Accessories', 100);

insert into customer_details values (101, 'Ravi Mehta', 'ravi@gmail.com', to_date('2023-01-10','yyyy-mm-dd'));
insert into customer_details values (102, 'Aarti Rao', 'aarti@gmail.com', to_date('2023-05-15','yyyy-mm-dd'));
insert into customer_details values (103, 'Vikas Shetty', 'vikas@gmail.com', to_date('2024-02-28','yyyy-mm-dd'));
insert into customer_details values (104, 'Neha Yadav', 'neha@gmail.com', to_date('2022-12-01','yyyy-mm-dd'));

select * from customer_details;
select * from products_master;

-- List all customers who purchased items that exist in the product master list.
select c.customer_id, c.item_purchased, p.item_name, c.purchase_amount_usd
from customers111 c
join products_master p on c.item_purchased = p.item_name;

-- Show all purchases made, and if the item is missing in master list, still show it.
select c.customer_id, c.item_purchased, p.category, c.purchase_amount_usd
from customers111 c
left join products_master p on c.item_purchased = p.item_name;

-- List all product master items and match purchases, even if never sold.
select p.item_name, p.category, c.customer_id
from customers111 c
right join products_master p on c.item_purchased = p.item_name;

-- Generate a list of all possible customer and product combinations to explore cross-sell opportunities.
select c.customer_id, c.item_purchased as current_purchase, p.item_name as suggested_product
from customers111 c
cross join products_master p;

-- Find pairs of customers who purchased the same item.
select a.customer_id as customer_1, b.customer_id as customer_2, a.item_purchased
from customers111 a
join customers111 b
on a.item_purchased = b.item_purchased where a.customer_id < b.customer_id;







